// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: pkg/discovery/discovery.proto

package discovery

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PublishMQTTMessageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Topic   string `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Payload []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"` // payload is encoded in whatever the entity needs.
}

func (x *PublishMQTTMessageRequest) Reset() {
	*x = PublishMQTTMessageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_discovery_discovery_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublishMQTTMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishMQTTMessageRequest) ProtoMessage() {}

func (x *PublishMQTTMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_discovery_discovery_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishMQTTMessageRequest.ProtoReflect.Descriptor instead.
func (*PublishMQTTMessageRequest) Descriptor() ([]byte, []int) {
	return file_pkg_discovery_discovery_proto_rawDescGZIP(), []int{0}
}

func (x *PublishMQTTMessageRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *PublishMQTTMessageRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type PublishMQTTMessageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
}

func (x *PublishMQTTMessageResponse) Reset() {
	*x = PublishMQTTMessageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_discovery_discovery_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublishMQTTMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishMQTTMessageResponse) ProtoMessage() {}

func (x *PublishMQTTMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_discovery_discovery_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishMQTTMessageResponse.ProtoReflect.Descriptor instead.
func (*PublishMQTTMessageResponse) Descriptor() ([]byte, []int) {
	return file_pkg_discovery_discovery_proto_rawDescGZIP(), []int{1}
}

func (x *PublishMQTTMessageResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_pkg_discovery_discovery_proto protoreflect.FileDescriptor

var file_pkg_discovery_discovery_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x70, 0x6b, 0x67, 0x2f, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x2f,
	0x64, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x4b, 0x0a, 0x19, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x4d, 0x51, 0x54, 0x54, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x6f, 0x70, 0x69, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x70,
	0x69, 0x63, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x2c, 0x0a, 0x1a,
	0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x4d, 0x51, 0x54, 0x54, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x32, 0x5a, 0x0a, 0x09, 0x64, 0x69,
	0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x12, 0x4d, 0x0a, 0x12, 0x50, 0x75, 0x62, 0x6c, 0x69,
	0x73, 0x68, 0x4d, 0x51, 0x54, 0x54, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x2e,
	0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x4d, 0x51, 0x54, 0x54, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x50, 0x75, 0x62, 0x6c,
	0x69, 0x73, 0x68, 0x4d, 0x51, 0x54, 0x54, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x2c, 0x5a, 0x2a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x65, 0x73, 0x6b, 0x70, 0x69, 0x6c, 0x2f, 0x74, 0x75, 0x6c, 0x69,
	0x70, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x64, 0x69, 0x73, 0x63, 0x6f,
	0x76, 0x65, 0x72, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_discovery_discovery_proto_rawDescOnce sync.Once
	file_pkg_discovery_discovery_proto_rawDescData = file_pkg_discovery_discovery_proto_rawDesc
)

func file_pkg_discovery_discovery_proto_rawDescGZIP() []byte {
	file_pkg_discovery_discovery_proto_rawDescOnce.Do(func() {
		file_pkg_discovery_discovery_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_discovery_discovery_proto_rawDescData)
	})
	return file_pkg_discovery_discovery_proto_rawDescData
}

var file_pkg_discovery_discovery_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_discovery_discovery_proto_goTypes = []interface{}{
	(*PublishMQTTMessageRequest)(nil),  // 0: PublishMQTTMessageRequest
	(*PublishMQTTMessageResponse)(nil), // 1: PublishMQTTMessageResponse
}
var file_pkg_discovery_discovery_proto_depIdxs = []int32{
	0, // 0: discovery.PublishMQTTMessage:input_type -> PublishMQTTMessageRequest
	1, // 1: discovery.PublishMQTTMessage:output_type -> PublishMQTTMessageResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_discovery_discovery_proto_init() }
func file_pkg_discovery_discovery_proto_init() {
	if File_pkg_discovery_discovery_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_discovery_discovery_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublishMQTTMessageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_discovery_discovery_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublishMQTTMessageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_discovery_discovery_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_discovery_discovery_proto_goTypes,
		DependencyIndexes: file_pkg_discovery_discovery_proto_depIdxs,
		MessageInfos:      file_pkg_discovery_discovery_proto_msgTypes,
	}.Build()
	File_pkg_discovery_discovery_proto = out.File
	file_pkg_discovery_discovery_proto_rawDesc = nil
	file_pkg_discovery_discovery_proto_goTypes = nil
	file_pkg_discovery_discovery_proto_depIdxs = nil
}
